/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author JonatanVT
 */
public class ViewMayor extends javax.swing.JPanel {

    /**
     * Creates new form ViewMayor
     */
    public ViewMayor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_n3 = new javax.swing.JLabel();
        jlb_resultado = new javax.swing.JLabel();
        jtf_n1 = new javax.swing.JTextField();
        jtf_n2 = new javax.swing.JTextField();
        jtf_n3 = new javax.swing.JTextField();
        jbtn_calcular = new javax.swing.JButton();
        jlb_n1 = new javax.swing.JLabel();
        jlb_numero_2 = new javax.swing.JLabel();

        jlb_n3.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_n3.setForeground(new java.awt.Color(204, 204, 204));
        jlb_n3.setText("N3:");

        jlb_resultado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_resultado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_resultado.setText("MVCPrincipal");

        jtf_n1.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_n1.setForeground(new java.awt.Color(204, 204, 204));

        jtf_n2.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_n2.setForeground(new java.awt.Color(204, 204, 204));

        jtf_n3.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_n3.setForeground(new java.awt.Color(204, 204, 204));

        jbtn_calcular.setBackground(new java.awt.Color(102, 153, 255));
        jbtn_calcular.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_calcular.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_calcular.setText("Calcular");

        jlb_n1.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_n1.setForeground(new java.awt.Color(204, 204, 204));
        jlb_n1.setText("N1:");

        jlb_numero_2.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_numero_2.setForeground(new java.awt.Color(204, 204, 204));
        jlb_numero_2.setText("N2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_n3)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlb_n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlb_numero_2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_n1)
                            .addComponent(jtf_n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero_2)
                            .addComponent(jtf_n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_n3)
                            .addComponent(jtf_n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_calcular;
    public javax.swing.JLabel jlb_n1;
    public javax.swing.JLabel jlb_n3;
    public javax.swing.JLabel jlb_numero_2;
    public javax.swing.JLabel jlb_resultado;
    public javax.swing.JTextField jtf_n1;
    public javax.swing.JTextField jtf_n2;
    public javax.swing.JTextField jtf_n3;
    // End of variables declaration//GEN-END:variables
}
